# Generated by Django 6.0 on 2025-12-31 19:30

import reporting.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='file',
            field=models.FileField(upload_to='evidence/%Y/%m/%d/', validators=[reporting.validators.validate_evidence_file]),
        ),
    ]
