# Generated by Django 5.1.1 on 2026-01-01 21:35

import reporting.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_crimereport_is_escalated_crimereport_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimereport',
            name='severity',
            field=models.CharField(choices=[('MINOR', 'Minor Impact'), ('MODERATE', 'Moderate Impact'), ('SIGNIFICANT', 'Significant Impact'), ('CATASTROPHIC', 'Catastrophic Impact')], default='MODERATE', max_length=20),
        ),
        migrations.AddField(
            model_name='evidence',
            name='is_investigator_added',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evidence',
            name='source_url',
            field=models.URLField(blank=True, help_text='Link to external evidence (e.g. social media profile, drive link)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investigationnote',
            name='is_internal',
            field=models.BooleanField(default=True, help_text='If true, only officers and admins see this note.'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='evidence/%Y/%m/%d/', validators=[reporting.validators.validate_evidence_file]),
        ),
    ]
