# Generated by Django 5.1.1 on 2026-01-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0002_user_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alternate_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='org_role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Organization Admin'), ('STAFF', 'Staff Member'), ('VIEWER', 'Viewer')], help_text='Role within the organization (if applicable)', max_length=20, null=True),
        ),
    ]
