# Generated by Django 5.1.1 on 2026-01-01 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0003_user_alternate_contact_user_org_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationprofile',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Admin approval status for organization registration'),
        ),
    ]
